### ISSUE TITLE
Error: Authentication is not configured for provider. Please configure it

### ISSUE THREAD

**Issue by rohitBaravkar** [samgabrail/databricks-azure#1]
Hi,

I am creating data bricks with the provider version mention below in the azure DevOps pipeline.
version = "0.3.1" for databricks
version = "2.29.0" for azure 

i m login to az cli first then terraform init and plan
![terraform-pipeline](https://user-images.githubusercontent.com/16099571/109803571-3645d300-7c47-11eb-91b6-7b04970efa2d.jpg)
.
Getting authentication error in plan.

**Comment by samgabrail** [comment]
@rohitBaravkar, thanks for your note here, but we're running this in Terraform Cloud. Authentication is defined in Terraform cloud as environment variables.
